### ISSUE TITLE
Google announces Kotlin for Android | Google I/O 2017

### ISSUE THREAD

**Issue by sschmid** [darkoverlordofdata/entitas-kotlin#1]
Google announces Kotlin for Android | Google I/O 2017

Here's the YouTube link
https://www.youtube.com/watch?v=d8ALcQiuPWs

Great to see there's an Entitas port already 😀

**Comment by darkoverlordofdata** [comment]
I like Kotlin. But all the tooling is java, which I find frustrating and difficult and slow to use.  But maybe better integration with Android Studio helps. I need to try it out again.
